sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 49.235.118.160
    port: 10001
    database: sky_take_out
    username: root
    password: 123456
  wechat:
    appid: 	wxea092986a05d4f07
    secret: 60059dc3120b2b22cf934b2c5cb4a74b